### ISSUE TITLE
Can I use this dataset for 3D Gaussian Splatting to perform three-dimensional reconstruction?

### ISSUE THREAD

**Issue by jiangyijin** [tpark94/shirt#1]
Hello, thank you for creating the dataset. I have downloaded your dataset. However, I am having trouble understanding the camera pose parameters in the dataset, specifically the q_vbs2tango_true and r_Vo2To_vbs_true. Could you please explain the specific coordinate system transformation from which coordinate system to which coordinate system these parameters represent? I have been struggling with this issue for a week now as I cannot perform 3D reconstruction using these poses directly. I would greatly appreciate it if you could help clarify my doubts. Here is the code I am using to handle camera poses.https://github.com/graphdeco-inria/gaussian-splatting/issues/719#issue-2198958106

**Comment by jiangyijin** [comment]
I also want to ask whether the images and camera poses related to the SPEED and SPEED+ datasets can be used for 3D reconstruction. I have visualized these camera poses in 3D space, and the distribution of camera poses and positions is the same as in your paper. However, I have been unable to carry out the 3D reconstruction.

**Comment by tpark94** [comment]
Hello,

Please see the following from the `METADATA.md` file.

- `pri` origin coincides with the center of mass (`com`). `bdy` origin is the origin of a CAD model and may not coincide with `com`.
- `r_A2B_C` refers to a position vector from point `A` to `B` expressed in reference frame `C`. If `A` and `B` are reference frames, the vector goes from the origin of `A` to that of `B`.
- `q_A2B` refers to a quaternion representing a rotation aligning the frame `A` with the frame `B`. The quaternion is scalar-first, i.e., `q = [qw, qx, qy, qz]`.

The naming of pose labels follows those of the previous SPEED and SPEED+ datasets. In the parlance of SHIRT metadata, those would correspond respectively to `q_scam2tbdy` and `r_scam2tbdy_scam`, i.e., they map the pose of the target's `bdy` frame w.r.t. the servicer's camera (`cam`) frame.

You can use the dataset for whatever purpose you'd like as long as they conform to the license.

**Comment by jiangyijin** [comment]
Thank you for your question. Based on my understanding, the q_vbs2tango_true and r_Vo2To_vbs_true values in the jest.json, roe1.json, and other JSON files in SPEED, SPEED+, and SHIRT are the servicer's camera (cam) poses relative to the target.

**Comment by jiangyijin** [comment]
I'm a bit confused with all the different coordinate systems, making it hard for me to understand their relationships clearly. Thank you very much for helping me with my questions.
